Add python bindings for BBProcessorFilter
google/gematria pull request #163
Opened 2024-07-28 20:17 UTC by boomanaiden154

This patch adds python bindings for BBProcessorFilter so that the tooling can be used within a Beam pipeline to process the basic blocks prior to annotation.

2024-07-28 21:52 UTC, boomanaiden154 commented
This is a stacked PR on #161.

2024-08-01 21:45 UTC, ondrasej requested changes

2024-08-01 21:45 UTC, ondrasej commented on gematria/datasets/python/process_and_filter_bbs.cc
> +// Copyright 2023 Google Inc.
2024

2024-08-01 21:45 UTC, ondrasej commented on gematria/datasets/python/process_and_filter_bbs.cc
> +          R"(Processes a raw basic block extracted from a ELF file.
Very nit: a**n** ELF file

2024-08-01 21:45 UTC, ondrasej commented on gematria/datasets/python/process_and_filter_bbs_test.py
> +    self.assertEqual(processed_bb, "B801000000")
We should also have at least one test that raises the exception.

2024-08-04 21:21 UTC, ondrasej approved these changes

2024-08-04 23:59 UTC, merged