Refactor utility to get llvm binary paths to common location
google/gematria pull request #186
Opened 2024-09-03 05:36 UTC by boomanaiden154

This patch refactors utilities to get LLVM binary paths, like opt and llc, to a common location. This should make maintenance slightly easier. It also gives us a central location where we can override how these are found, to adapt for internal differences.

2024-09-03 07:34 UTC, ondrasej requested changes
Overall, this makes sense. But I'd prefer to make this a bit more specific (to avoid situations where we have one library that pulls in all the binaries used throughout the project, even if only one of them is used).

2024-09-03 07:34 UTC, ondrasej commented on gematria/utils/python/runfiles.py
I'd prefer to put this somewhere under `gematria/llvm/...`. I don't think we want to add any other (non-LLVM) binaries to this library, because it would mean that everyone who uses one of them needs to carry over all others, even if they are never used.

Maybe we should have one library per tool even for the LLVM tools, but let's do that only when we need to use the tools separately.

2024-09-03 19:29 UTC, boomanaiden154 commented on gematria/utils/python/runfiles.py
The binaries aren't getting added against the library. The idea is to keep them in the `data` tag of the binary/library actually using them, and just use this as a lookup function that we can easily override internally.

2024-09-12 08:21 UTC, ondrasej approved these changes

2024-09-12 08:21 UTC, ondrasej commented on gematria/llvm/python/runfiles.py
> +def get_llvm_binary_path(tool_name: str) -> str:
Nit: Please add a docstring.

2024-09-13 13:24 UTC, merged