Add extra checks to select the right mapping and filter samples within it.
google/gematria pull request #266
Opened 2024-12-18 14:04 UTC by virajbshah

* Add a binary name check while identifying the main mapping.
 * A new check of the sample PID against the main mapping PID.
 * Remove the check for whether the block's code was within the bounds
   of the executable segment in terms of file addresses, this is
   redundant as long as the mapping is valid.

2024-12-20 10:15 UTC, ondrasej requested changes

2024-12-20 10:15 UTC, ondrasej commented on gematria/datasets/annotating_importer.cc
> +      continue;
Very nit: Please put braces around this statement, for consistency with the rest of the code.

2024-12-20 10:15 UTC, ondrasej commented on gematria/datasets/annotating_importer.cc
> +std::string GetFileNameFromPath(const std::string &path) {
Nit: This is usually called "Basename" in the unix world.

2025-02-07 14:05 UTC, ondrasej approved these changes

2025-02-07 14:05 UTC, ondrasej commented on gematria/datasets/annotating_importer.cc
> +constexpr int kProtExec = 0b100;  /* PROT_EXEC */
Can we use `PROT_READ`, `PROT_WRITE`, and `PROT_EXEC` directly in our code?

Normally, they should be provided by `sys/mman.h` - and if they are, I'd go for the system definitions rather than define our own.

2025-02-07 15:37 UTC, virajbshah commented on gematria/datasets/annotating_importer.cc
> +constexpr int kProtExec = 0b100;  /* PROT_EXEC */
They are indeed provided by `sys/mman.h`, but I opted to define them here with the comment pointing to `sys/mman.h` so that it doesn't stop this from being built on Windows. I _could_ use a `__has_include(<sys/mman.h>)` with a preprocessor macro at the top to use `sys/mman.h` whenever possible and just define `PROT_{READ,WRITE,EXEC}` otherwise. Or would simply dropping Windows compatibility make more sense?

2025-02-07 15:54 UTC, ondrasej commented on gematria/datasets/annotating_importer.cc
> +constexpr int kProtExec = 0b100;  /* PROT_EXEC */
We already have a Linux-only (POSIX maybe) dependency with finding accessed addresses, so I'm not too worried about that.

But we could do the `__has_include` check and include it if defined, otherwise take our own definitions.

2025-02-17 14:54 UTC, merged