Error out if we try to annotate a zero address
google/gematria pull request #72
Opened 2024-03-14 02:45 UTC by boomanaiden154

This patch makes the exegesis annotator error out if we try to map the zero address as we are not able to do this with mmap. To solve this while still being able to annotate the blocks, we probably need some way to adjust the register/memory values.

2024-03-14 13:10 UTC, ondrasej requested changes

2024-03-14 19:58 UTC, boomanaiden154 commented on gematria/datasets/find_accessed_addrs_exegesis.cc
> +          uintptr_t MapAddress = (CrashInfo.getAddress() & ~0xfff);
Good point. This patch just happens to move that code (which was already there), so I'm not sure it's relevant here. I'll open up another patch to address this specific problem.

2024-03-18 14:33 UTC, ondrasej approved these changes

2024-03-18 14:33 UTC, ondrasej commented on gematria/datasets/find_accessed_addrs_exegesis.cc
> +          uintptr_t MapAddress = (CrashInfo.getAddress() & ~0xfff);
Ack.

2024-03-18 18:49 UTC, merged