Add support for instruction annotations to the graph builder.
google/gematria pull request #93
Opened 2024-03-26 21:37 UTC by virajbshah

Allows `BasicBlockGraphBuilder` to store instruction annotations in a vector-of-vector matrix while processing instructions to build graphs, so that they are available to graph builder based models. The list of names of annotation types to be stored is supplied at the time of construction of the graph builder.

2024-04-28 19:24 UTC, ondrasej requested changes

2024-04-28 19:24 UTC, ondrasej commented on gematria/granite/python/graph_builder_test.py
Please update also `BasicBlockBuilderTest.assertBuilderIsSelfConsistent()` (that mainly checks dimensions of all the generated vectors and matrices, so we should have the same for the annotations).

2024-04-28 19:24 UTC, ondrasej commented on gematria/testing/testdata/annotated_basic_blocks_with_throughput.pbtxt
Where do the blocks come from? Do we need to worry about licenses/origins/...?

2024-05-13 12:23 UTC, virajbshah commented on gematria/testing/testdata/annotated_basic_blocks_with_throughput.pbtxt
They are the same blocks as those from `basic_blocks_with_throughput.pbtxt`, just with (random) annotations - so I don't think there should be any concerns.

2024-07-22 08:56 UTC, merged